# Generated by Django 4.1.6 on 2023-02-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bapp", "0002_login_register_alter_events_event_description"),
    ]

    operations = [
        migrations.DeleteModel(name="login",),
        migrations.RenameField(
            model_name="register", old_name="fname", new_name="userid",
        ),
        migrations.RemoveField(model_name="register", name="lname",),
    ]
