# Generated by Django 4.1.6 on 2023-02-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bapp", "0006_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
